name: AWS Lambda Code Signing GitHub Action
author: Clowd Haus, LLC
description: GitHub action which uses AWS Code Signer to sign âœðŸ¼ AWS Lambda artifacts ðŸ“¦ from your pipeline
branding:
  icon: edit
  color: orange

inputs:
  aws-region:
    description: AWS Region, e.g. us-east-2
    required: true
  client-request-token:
    description: >-
      String that identifies the signing request. All calls after
      the first that use this token return the same response as the first call
    required: false
  source-s3-bucket:
    description: The S3 bucket that contains the object to sign
    required: true
  source-s3-key:
    description: Key name of the bucket object that contains your unsigned code
    required: true
  source-s3-version:
    description: Version of your source image in your version enabled S3 bucket
    required: true
  destination-s3-bucket:
    description: The S3 bucket in which to save your signed object
    required: true
  destination-s3-prefix:
    description: S3 object key prefix to prepend to your signed object
    required: false
    default: 'signed/'
  profile-name:
    description: The name of the signing profile
    required: true
  profile-owner:
    description: The AWS account ID of the signing profile owner
    required: false
  rename-signed-object:
    description: >-
      Rename the generated signed object to match the original
      `sourceS3Key` with the `destinationS3Prefix`
    required: false
    default: 'true'
  wait-until-successful:
    description: Wait until the signed jobs complete successfully
    required: false
    default: 'true'
  max-wait-time:
    description: >-
      Maximum amount of time, in seconds, to wait for a job to complete successfully
    required: false
    default: '30'

outputs:
  job-id:
    description: The ID of your signing job
  signed-object-key:
    description: The S3 key of your signed object, as created by AWS Signer
  renamed-signed-object-key:
    description: The renamed S3 key of your signed object

runs:
  using: 'node16'
  main: 'dist/index.js'
